### PR TITLE
Issue #4: Fix collapse error (Uncaught TypeError: $.camelCase is not a function).

### LINKED ISSUE #4: Uncaught TypeError: $.camelCase is not a function
First of all, thanks a lot for this effort, I've been using this project to make my [Drupal Bootstrap 3 theme](https://www.drupal.org/project/estore/) to make it work in D11, so far I've managed to make the main menu to work again, among other features, but the collapse functionality is not working for me, I tried to use it to display the search bar and I get this issue: 

```
Uncaught TypeError: $.camelCase is not a function
    at Collapse.show (bootstrap.js?svv6vg:710:24)
    at Collapse.toggle (bootstrap.js?svv6vg:756:57)
    at new Collapse (bootstrap.js?svv6vg:650:35)
    at HTMLDivElement.<anonymous> (bootstrap.js?svv6vg:797:52)
    at T.each (jquery.min.js?v=4.0.0-beta.2:2:2876)
    at T.fn.init.each (jquery.min.js?v=4.0.0-beta.2:2:1386)
    at T.fn.init.Plugin [as collapse] (bootstrap.js?svv6vg:791:17)
    at HTMLButtonElement.<anonymous> (bootstrap.js?svv6vg:829:12)
    at HTMLDocument.dispatch (jquery.min.js?v=4.0.0-beta.2:2:38062)
    at v.handle (jquery.min.js?v=4.0.0-beta.2:2:36042)
```

It seems like this proyect is calling a jQuery [function that was deprecated back in 2016](https://github.com/jquery/jquery/issues/3384)

I'll attempt to implement this function in this project, because I really need it.

The Drupal issue just in case: https://www.drupal.org/project/estore/issues/3522990

I looked at your [contributing guide ](https://github.com/entreprise7pro/bootstrap/blob/v3-dev/CONTRIBUTING.md)and it seems like there are a lot of restrictions when it comes to create a pull request, please let me know so I fork this project to fix this issue for my project.

### PR DESCRIPTION
**Pull request by vever001**
jQuery camelCase was deprecated and now removed in 4.0.0.

Fixes https://github.com/entreprise7pro/bootstrap/issues/4

### CODE REVIEW

File: js/collapse.js [hunk 1]
```diff
@@ -89,7 +89,7 @@
 
     if (!$.support.transition) return complete.call(this)
 
-    var scrollSize = $.camelCase(['scroll', dimension].join('-'))
+    var scrollSize = 'scroll' + (dimension === 'width' ? 'Width' : 'Height')
```
Comment (vever001) [inline js/collapse.js:92]: Naturally, there are other ways like
```
var scrollSize = ['scroll', dimension].join('-').replace(/-([a-z])/g, (match, letter) => letter.toUpperCase())
```

But I opted for the simplest fix since we know dimension can only be 'width' or 'height'.
Any preference?

**Comment by joejoseph00** [comment]
Ok great thanks for this.  Merged

**Comment by joejoseph00** [comment]
https://www.npmjs.com/package/entreprise7pro-bootstrap  ok I published 3.4.7 as a release, test this out.  If it's good I'll update the drupal bootstrap theme to use it.
